# Generated by Django 6.0.4 on 2026-04-27 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_categorias_producto_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorias',
            options={'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='ordenes',
            options={'verbose_name_plural': 'Ordenes'},
        ),
    ]
